# Generated by Django 3.1.14 on 2023-06-29 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230630_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 1, 50, 45, 975209)),
        ),
    ]
