# Generated by Django 3.1.14 on 2023-06-29 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='current_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 30, 1, 51, 39, 166177)),
        ),
    ]
