# Generated by Django 3.1.14 on 2023-06-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20230630_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='current_time',
        ),
    ]
