# Generated by Django 3.1.14 on 2023-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230625_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
