# Generated by Django 3.1.14 on 2023-06-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemonentity_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='is_active',
        ),
    ]
